title: "oOtroyOo Blog"
description: "A Jekyll theme based on MDUI"
url: 
baseurl: "/blog-mdui"
author: "oOtroyOo"
paginate: 5
paginate_path: "/blog-mdui/blog/page:num/"
serviceWorker : true 

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs