title: "做一个简单的大佬"
description: "oOtroyOo Blog"
url: 
baseurl: "/blog-mdui"
author: "oOtroyOo"
paginate: 5
paginate_path: "/blog-mdui/blog/page:num/"
serviceWorker : fase 
beian : "蜀ICP备18009358号-1"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs